#!/bin/bash
user="vitaly"

docker build -t jupyter --build-arg user=${user} .

docker run -d \
    --rm \
    --name jupyter \
    --gpus all \
    -e USER=${user} \
    -p 80:80 \
    -v ${PWD}/data:/home/${user} \
    -v ${PWD}/config:/srv/jupyterhub \
    jupyter
