#!/bin/bash

set -eu

docker build -t jupyter .

VOLUME="jupyter"

if ! docker volume inspect $VOLUME; then
    docker volume create --driver local \
        --opt type=none \
        --opt device=$PWD/data \
        --opt o=bind \
        $VOLUME
fi

docker run \
    -d \
    --rm \
    -it \
    --name jupyter \
    --gpus all \
    -e NVIDIA_VISIBLE_DEVICES=all \
    -e NVIDIA_DRIVER_CAPABILITIES=all \
    -p 8888:8888 \
    -v $VOLUME:/home/jovyan/work \
    jupyter
